version: '3.9'
services:
  cms_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 43210:3000
    volumes:
      - type: bind
        source: $PWD
        target: /usr/src/app
  mongo:
    image: 'mongo:4.4.14'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
